name: BayesFunc
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>=3.9.1
  - pip>=20.3.3
  - six>=1.15.0
  - numpy>=1.19.2
  - matplotlib>=3.3.3
  - jupyter>=1.0.0
  - pytorch>=1.7.1
  - torchvision>=0.8.2
  - pip:
    - -e .
